
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.2'

_lr_method = 'LALR'

_lr_signature = b'\xe0\xbb\xa18\xdb\x0b\xed{;\xff\x9b\x0cl\xc9\x91.'
    
_lr_action_items = {'PLUS':([1,4,9,10,11,12,13,14,15,],[6,-1,6,-2,-7,-4,-6,-5,-3,]),'RPAREN':([4,9,10,11,12,13,14,15,],[-1,15,-2,-7,-4,-6,-5,-3,]),'TIMES':([1,4,9,10,11,12,13,14,15,],[7,-1,7,-2,-7,7,-6,7,-3,]),'$end':([1,4,10,11,12,13,14,15,],[0,-1,-2,-7,-4,-6,-5,-3,]),'DIVIDE':([1,4,9,10,11,12,13,14,15,],[5,-1,5,-2,-7,5,-6,5,-3,]),'LPAREN':([0,2,5,6,7,8,],[2,2,2,2,2,2,]),'MINUS':([0,1,2,4,5,6,7,8,9,10,11,12,13,14,15,],[3,8,3,-1,3,3,3,3,8,-2,-7,-4,-6,-5,-3,]),'NUMBER':([0,2,3,5,6,7,8,],[4,4,10,4,4,4,4,]),}

_lr_action = { }
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = { }
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'expression':([0,2,5,6,7,8,],[1,9,11,12,13,14,]),}

_lr_goto = { }
for _k, _v in _lr_goto_items.items():
   for _x,_y in zip(_v[0],_v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = { }
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> expression","S'",1,None,None,None),
  ('expression -> NUMBER','expression',1,'p_expression','/Users/Noah/Repositories/rocket/rocketyacc.py',17),
  ('expression -> MINUS NUMBER','expression',2,'p_expression','/Users/Noah/Repositories/rocket/rocketyacc.py',18),
  ('expression -> LPAREN expression RPAREN','expression',3,'p_expression','/Users/Noah/Repositories/rocket/rocketyacc.py',19),
  ('expression -> expression PLUS expression','expression',3,'p_expression','/Users/Noah/Repositories/rocket/rocketyacc.py',20),
  ('expression -> expression MINUS expression','expression',3,'p_expression','/Users/Noah/Repositories/rocket/rocketyacc.py',21),
  ('expression -> expression TIMES expression','expression',3,'p_expression','/Users/Noah/Repositories/rocket/rocketyacc.py',22),
  ('expression -> expression DIVIDE expression','expression',3,'p_expression','/Users/Noah/Repositories/rocket/rocketyacc.py',23),
]
