
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.2'

_lr_method = 'LALR'

_lr_signature = b'\x0b\xb7YN\x0f\xc6!\x9beN\x02\x91\xdeP\x9d\xd0'
    
_lr_action_items = {'DIVIDE':([1,4,5,6,11,12,13,14,15,],[-2,10,10,-1,-3,-6,10,10,-7,]),'RPAREN':([1,5,6,11,12,13,14,15,],[-2,11,-1,-3,-6,-5,-4,-7,]),'TIMES':([1,4,5,6,11,12,13,14,15,],[-2,7,7,-1,-3,-6,7,7,-7,]),'NUMBER':([0,2,3,7,8,9,10,],[1,1,1,1,1,1,1,]),'$end':([1,4,6,11,12,13,14,15,],[-2,0,-1,-3,-6,-5,-4,-7,]),'MINUS':([0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,],[3,-2,3,3,8,8,-1,3,3,3,3,-3,-6,-5,-4,-7,]),'PLUS':([1,4,5,6,11,12,13,14,15,],[-2,9,9,-1,-3,-6,-5,-4,-7,]),'LPAREN':([0,2,3,7,8,9,10,],[2,2,2,2,2,2,2,]),}

_lr_action = { }
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = { }
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'expression':([0,2,3,7,8,9,10,],[4,5,6,12,13,14,15,]),}

_lr_goto = { }
for _k, _v in _lr_goto_items.items():
   for _x,_y in zip(_v[0],_v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = { }
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> expression","S'",1,None,None,None),
  ('expression -> MINUS expression','expression',2,'p_uminus','/Users/Noah/Repositories/rocket/rocketyacc.py',17),
  ('expression -> NUMBER','expression',1,'p_expression','/Users/Noah/Repositories/rocket/rocketyacc.py',21),
  ('expression -> LPAREN expression RPAREN','expression',3,'p_expression','/Users/Noah/Repositories/rocket/rocketyacc.py',22),
  ('expression -> expression PLUS expression','expression',3,'p_expression','/Users/Noah/Repositories/rocket/rocketyacc.py',23),
  ('expression -> expression MINUS expression','expression',3,'p_expression','/Users/Noah/Repositories/rocket/rocketyacc.py',24),
  ('expression -> expression TIMES expression','expression',3,'p_expression','/Users/Noah/Repositories/rocket/rocketyacc.py',25),
  ('expression -> expression DIVIDE expression','expression',3,'p_expression','/Users/Noah/Repositories/rocket/rocketyacc.py',26),
]
